### ISSUE TITLE
Plugin clashes with the collection log plugin.

### ISSUE THREAD

**Issue by jlkjlkjkljkljlkjkljkljkl** [Pfannaa/FunnyBossNames#1]
Hello, I like the funny boss name plugin, however it seems to clash with the collection log plugin which automatically uploads collection log data to their website.

Since the funny boss names plugin changes the names on the collectoin log as well it seems to not be able to upload the data properly to the collection log data website.

My request is if it could be so that the names on the collection log no longer change, perhaps with a setting toggle

**Comment by Pfannaa** [comment]
Hey, thanks for bringing this up! 
I'll look into this soon.

**Comment by Pfannaa** [comment]
Currently waiting for the PR to be merged.

**Comment by Pfannaa** [comment]
PR got merged some time ago, should work flawless now
